Repository ibm-ecosystem-engineering/watsonx-demo-svc, pull requests merged in 2023-09, with the labels that each got.

#8 Fix configuration in Dockerfile and docker-build workflow
  .github/workflows/docker-build.yaml
  Dockerfile
Labels: bug, patch

#9 Update dependencies
  .github/workflows/docker-build.yaml
  package-lock.json
  package.json
Labels: patch, chore

#10 Read csv config from file
  config/KYCDataValidationQuestions.csv
  src/services/data-extraction/data-extraction.csv.ts
  src/services/data-extraction/data-extraction.impl.ts
  src/services/data-extraction/data-extraction.mock.ts
Labels: enhancement, minor

#11 Fix command to run app in Dockerfile
  Dockerfile
Labels: bug, patch

#12 Add REST api and swagger docs for data extraction
  package-lock.json
  package.json
  src/controllers/data-extraction/data-extraction.controller.ts
  src/controllers/data-extraction/index.ts
  src/controllers/index.ts
  src/main.ts
Labels: enhancement, minor

#13 Add log messages for data extraction steps
  src/services/data-extraction/data-extraction.impl.ts
Labels: patch, chore

#19 Update questionIds definition to fix problem
  src/controllers/data-extraction/data-extraction.controller.ts
Labels: bug, patch

#20 Update data-extraction discovery logic
  config/KYCDataValidationQuestions.csv
  src/controllers/data-extraction/data-extraction.controller.ts
  src/services/data-extraction/data-extraction.csv.ts
  src/services/data-extraction/data-extraction.impl.ts
Labels: bug, patch

#21 Update workflow and variables to auto deploy when image published
  .github/workflows/deploy-image.yaml
  .github/workflows/docker-build.yaml
Labels: patch, chore

#23 Fix var references in deploy-image workflow
  .github/workflows/deploy-image.yaml
Labels: patch, chore

#22 Update logic for data extract
  src/controllers/data-extraction/data-extraction.controller.ts
  src/services/data-extraction/data-extraction.impl.ts
Labels: bug, patch

#24 Set runas user for deploy-image
  .github/workflows/deploy-image.yaml
Labels: bug, chore

#25 Set HOME environment variable for image deploy
  .github/workflows/deploy-image.yaml
Labels: patch, chore

#26 Throttle discovery and llm calls for data-extraction and add cra api
  .env.template
  package-lock.json
  schema.gql
  src/config/customer-risk-assessment.config.ts
  src/config/index.ts
  src/controllers/customer-risk-assessment/customer-risk-assessment.controller.ts
  src/controllers/customer-risk-assessment/index.ts
  src/controllers/index.ts
  src/graphql-types/kyc-case.graphql.ts
  src/models/kyc-case.model.ts
  src/services/customer-risk-assessment/README.md
  src/services/customer-risk-assessment/api.ts
  src/services/customer-risk-assessment/apis/cp4admin-customer-risk-assessment-customer-risk-assessment-api.ts
  src/services/customer-risk-assessment/base.ts
  src/services/customer-risk-assessment/configuration.ts
  src/services/customer-risk-assessment/index.ts
  src/services/customer-risk-assessment/models/customer-risk-assessment-risk0020-assessment-input.ts
  src/services/customer-risk-assessment/models/customer-risk-assessment-risk0020-assessment-output.ts
  src/services/customer-risk-assessment/models/customer0020-risk0020-assessment-incident.ts
  src/services/customer-risk-assessment/models/index.ts
  src/services/data-extraction/data-extraction.csv.ts
  src/services/data-extraction/data-extraction.impl.ts
  src/services/kyc-case/kyc-case-management.mock.ts
  src/services/negative-news/negative-news.api.ts
  src/services/negative-news/negative-news.impl.ts
  src/utils/discovery-v2.ts
  src/utils/gen-ai-model.ts
  src/utils/p-queue/index.ts
  src/utils/p-queue/lower-bound.ts
  src/utils/p-queue/options.ts
  src/utils/p-queue/priority-queue.ts
  src/utils/p-queue/queue.ts
  src/utils/p-timeout/index.ts
Labels: enhancement, minor

#29 Fix credentials for CRA api call
  src/config/customer-risk-assessment.config.ts
  src/config/index.ts
  src/controllers/customer-risk-assessment/customer-risk-assessment.controller.ts
  src/controllers/kyc-summary/kyc-summary.controller.ts
  src/services/customer-risk-assessment/customer-risk-assessment.config.ts
  src/services/customer-risk-assessment/index.ts
  src/services/kyc-case-summary/index.ts
  src/services/kyc-case-summary/kyc-summary.config.ts
  src/services/kyc-case/kyc-case-management.mock.ts
  src/services/menu-options/menu-options.mock.ts
Labels: bug, patch

#30 Update kyc summary logic
  .env.template
  src/models/kyc-case.model.ts
  src/services/kyc-case/kyc-case-management.mock.ts
  src/services/menu-options/menu-options.mock.ts
Labels: enhancement, minor

#31 Add /document prefix to document path
  src/controllers/file-upload/file-upload.controller.ts
Labels: bug, patch

#32 Add /document prefix to document path
  src/controllers/file-upload/file-upload.controller.ts
  src/services/kyc-case/kyc-case-management.api.ts
  src/services/kyc-case/kyc-case-management.mock.ts
Labels: bug, patch

#33 Add service and endpoint to re-issue AI calls on case
  schema.gql
  src/resolvers/kyc-case/kyc-case.resolver.ts
  src/services/kyc-case/kyc-case-management.api.ts
  src/services/kyc-case/kyc-case-management.mock.ts
Labels: enhancement, minor

#34 Update dependencies
  package-lock.json
  package.json
Labels: patch, chore

#36 Fix logic for handling counterparty info
  src/services/kyc-case/kyc-case-management.mock.ts
Labels: bug, patch

#39 Remove duplicate country and filter list
  src/services/menu-options/menu-options.mock.ts
Labels: bug, patch

#41 Update kyc case summary with new backend api
  schema.gql
  src/controllers/kyc-summary/kyc-summary.controller.ts
  src/resolvers/kyc-case-summary/index.ts
  src/resolvers/kyc-case-summary/kyc-case-summary.resolver.ts
  src/resolvers/providers.ts
  src/services/kyc-case-summary/README.md
  src/services/kyc-case-summary/api.ts
  src/services/kyc-case-summary/apis/default-api-interface.ts
  src/services/kyc-case-summary/apis/default-api.ts
  src/services/kyc-case-summary/base.ts
  src/services/kyc-case-summary/configuration.ts
  src/services/kyc-case-summary/index.ts
  src/services/kyc-case-summary/kyc-case-summary.api.ts
  src/services/kyc-case-summary/kyc-case-summary.impl.ts
  src/services/kyc-case-summary/kyc-summary.config.ts
  src/services/kyc-case-summary/models/body-upload-financials-post.ts
  src/services/kyc-case-summary/models/entity.ts
  src/services/kyc-case-summary/models/httpvalidation-error.ts
  src/services/kyc-case-summary/models/index.ts
  src/services/kyc-case-summary/models/validation-error.ts
  src/services/kyc-case-summary/openapi.json
  src/services/kyc-case/kyc-case-management.mock.ts
  src/services/menu-options/index.ts
  src/services/providers.ts
Labels: bug

#46 Upload KYC and data extract discovery instances
  src/controllers/file-upload/file-upload.controller.ts
  src/models/index.ts
  src/services/data-extraction/data-extraction.impl.ts
  src/services/document-manager/document-manager.api.ts
  src/services/document-manager/document-manager.discovery.ts
  src/services/document-manager/index.ts
  src/services/kyc-case/kyc-case-management.mock.ts
Labels: enhancement, minor

#47 Update nestjs dependencies with patch releases
  package-lock.json
  package.json
Labels: patch, chore

#48 Implements negative news service
  .env.template
  config/filter.json
  config/news-cache.json
  config/topic_risk_score_config.json
  package-lock.json
  package.json
  schema.gql
  src/graphql-types/kyc-case.graphql.ts
  src/models/kyc-case.model.ts
  src/resolvers/negative-news/index.ts
  src/resolvers/negative-news/negative-news.resolver.ts
  src/resolvers/providers.ts
  src/services/data-extraction/data-extraction.impl.ts
  src/services/kyc-case/kyc-case-management.mock.ts
  src/services/negative-news/negative-news.api.ts
  src/services/negative-news/negative-news.impl.ts
  src/services/providers.ts
  src/services/web-scrape/index.ts
  src/services/web-scrape/web-scrape.api.ts
  src/services/web-scrape/web-scrape.hybrid.ts
  src/services/web-scrape/web-scrape.local.ts
  src/services/web-scrape/web-scrape.scrapeit.ts
  src/utils/gen-ai-model.ts
  src/utils/index.ts
  src/utils/validate-url.ts
Labels: enhancement, minor

#50 Update Data Extraction config logic
  src/services/data-extraction/data-extraction.csv.ts
  src/services/data-extraction/data-extraction.impl.ts
Labels: bug, patch

#51 Include LLM prompt in data extraction result
  schema.gql
  src/graphql-types/data-extraction.graphql.ts
  src/models/data-extraction.model.ts
  src/services/data-extraction/data-extraction.impl.ts
Labels: enhancement, minor

#52 Update handling of web-scrape caching
  nest-cli.json
  src/services/web-scrape/web-scrape.local.ts
Labels: bug, patch

#53 Throttle the requests to kyc-summary to 1 concurrent request
  src/services/kyc-case-summary/kyc-case-summary.impl.ts
Labels: bug, patch

#54 Throttle summary
  config/news-cache.json
  src/services/kyc-case/kyc-case-management.mock.ts
  src/utils/gen-ai-model.ts
Labels: bug, patch

#55 Add logic to retry watsonx call after 'Too many requests' error
  src/utils/gen-ai-model.ts
Labels: bug, patch

#61 Implement cloudant backend and update case processing
  .env.template
  package-lock.json
  package.json
  schema.gql
  src/app.module.ts
  src/graphql-types/kyc-case.graphql.ts
  src/lifecycle/case-processor.hook.ts
  src/lifecycle/index.ts
  src/models/kyc-case.model.ts
  src/resolvers/kyc-case/kyc-case.resolver.ts
  src/services/document-manager/index.ts
  src/services/kyc-case-summary/index.ts
  src/services/kyc-case/cloudant.backend.ts
  src/services/kyc-case/index.ts
  src/services/kyc-case/kyc-case-management.api.ts
  src/services/kyc-case/kyc-case-management.cloudant.ts
  src/services/kyc-case/kyc-case-management.mock.ts
  src/services/negative-news/index.ts
  src/services/negative-news/negative-news.impl.ts
  src/utils/stream-to-buffer.ts
Labels: enhancement, minor

#62 Update patch dependencies
  package-lock.json
  package.json
Labels: patch, chore

#63 Add service to retrieve document processing status
  schema.gql
  src/controllers/file-upload/file-upload.controller.ts
  src/graphql-types/kyc-case.graphql.ts
  src/resolvers/document-management/document-management.resolver.ts
  src/resolvers/document-management/index.ts
  src/resolvers/kyc-case/kyc-case.resolver.ts
  src/resolvers/providers.ts
  src/services/document-manager/document-manager.api.ts
  src/services/document-manager/document-manager.discovery.ts
  src/services/document-manager/document-manager.mock.ts
Labels: enhancement, minor

#64 Fix project id used for kyc-case file uploads
  src/services/document-manager/document-manager.discovery.ts
  src/services/kyc-case-summary/kyc-case-summary.impl.ts
Labels: bug, patch

#65 Fix args for listFiles() api call
  src/controllers/file-upload/file-upload.controller.ts
Labels: bug, patch

#70 Update listFiles() logic
  src/controllers/file-upload/file-upload.controller.ts
  src/services/document-manager/document-manager.api.ts
  src/services/document-manager/document-manager.discovery.ts
Labels: bug, patch

#72 Add filter to discovery query
  src/services/data-extraction/data-extraction.impl.ts
Labels: bug, patch
