Repository ibm-ecosystem-engineering/watsonx-demo-svc, pull requests merged in 2023-10, with the labels that each got.

#82 Update data extract logic
  Dockerfile
  src/services/data-extraction/data-extraction.impl.ts
Labels: bug, patch

#83 Update dependencies
  package-lock.json
  package.json
Labels: patch, chore

#84 Fix subscription logic
  config/news-cache.json
  src/resolvers/data-extraction/data-extraction.resolver.ts
  src/resolvers/kyc-case/kyc-case.resolver.ts
  src/services/kyc-case/kyc-case-management.cloudant.ts
Labels: bug, patch

#85 Kycdataextraction nck
  config/KYCDataValidationQuestions.csv
  src/services/data-extraction/data-extraction.impl.ts
Labels: patch, chore

#88 Apply correct status after customer outreach
  src/services/kyc-case/kyc-case-management.cloudant.ts
Labels: bug, patch

#96 Update data extract logic and config
  config/KYCDataValidationQuestions.csv
  schema.gql
  src/graphql-types/data-extraction.graphql.ts
  src/models/data-extraction.model.ts
  src/services/data-extraction/data-extraction.csv.ts
  src/services/data-extraction/data-extraction.impl.ts
  src/services/data-extraction/data-extraction.mock.ts
Labels: enhancement, minor

#98 Update config parameters for data extract
  config/KYCDataValidationQuestions.csv
  src/services/data-extraction/data-extraction.csv.ts
  src/services/data-extraction/data-extraction.impl.ts
Labels: bug, patch

#99 Strip html from discovery result and check for empty response
  package-lock.json
  package.json
  src/services/data-extraction/data-extraction.impl.ts
Labels: bug, patch

#103 Update dependencies
  package-lock.json
  package.json
Labels: patch, chore

#116 Add call to simiarity-check api to perform cosine similarity
  src/services/data-extraction/data-extraction.impl.ts
Labels: enhancement, minor

#118 Add throttling for cosine passage call
  src/services/data-extraction/data-extraction.impl.ts
Labels: bug, patch

#120 Reduce find relevant passage concurrent requests to 2
  src/services/data-extraction/data-extraction.impl.ts
Labels: bug, patch

#122 Handle errors from relevant passage api call
  src/services/data-extraction/data-extraction.impl.ts
Labels: bug, patch

#123 Update throttling
  src/resolvers/data-extraction/data-extraction.resolver.ts
  src/services/data-extraction/data-extraction.impl.ts
  src/utils/discovery-v2.ts
Labels: bug, patch

#124 Increase find passage concurrency to 8 and expose env variable
  src/services/data-extraction/data-extraction.impl.ts
Labels: bug, patch

#127 Strip tags if fall back to joined passages
  src/services/data-extraction/data-extraction.impl.ts
Labels: bug, patch
